### PR TITLE
simple-upnpd.skeleton.xml file for raspberrypi2

### PR DESCRIPTION
**Pull request by izak**
This minor allows simple-upnpd to build on a raspberrypi2.

### CODE REVIEW

**Comment by mpvader** [comment]
Hi, :::MAC::: seems to missing in a few places?

**Comment by jhofstee** [comment]
I guess a decent common solution would be to have a file with the unique id of the device in a file at a know location, so this package is not device specific. I can live with the id missing for the time being, lets see if I can come up with a more general short term solution...

**Comment by jhofstee** [comment]
how about this, https://github.com/victronenergy/meta-victronenergy/commit/3c26ec2dc2405ec29dd3308ce358f372d2403750?

mind it, git diff thinks the removal of the beaglebone file and adding the common file is a rewrite....

**Comment by jhofstee** [comment]
mmm well without the :::MAC:::. and I should update the commit message, it likely breaks having multiple devices on the same network.....

**Comment by mpvader** [comment]
Perhaps this is an idea: make all packages look for machine name (beaglebone, Ccgx, rapsberrypi) and the vrmportalid in /etc/venus. And in there we make a symlink to a static file in /data when practical. Or not, when not needed. That way it also works on systems (raspbian package based for example) that don't have /data. Or do they?

Dropping the unique idea now doesn't sound like a good idea to me. Why not simply fix up the rpi2 one and keep the existing structure until there is something better? It is no priority to improve this. A few files don't hurt.

**Comment by jhofstee** [comment]
Slightly off-topic. There are more things to consider actually in general. The modbus-tcp people find the ccgx by looking for the upnp announce. It would be nice if they can detect a compatible one I guess.

**Comment by jhofstee** [comment]
the beaglebone started dropping the MAC, not the rpi

**Comment by mpvader** [comment]
;). Stupid me. Welcome to fix that too. I can do quite a lot from my iPhone, but not changing this.

**Comment by mpvader** [comment]
Ha! Also this can be done from my iPhone. No testing though. And I left all ccgx references (modename, UDN) in place on purpose. Same like Achilles..

See pull request in a second

**Comment by mpvader** [comment]
Is in master, for details see commits there. thanks

**Comment by mpvader** [comment]
Also upnp was added to the raspbian builds / packages

**Pull request closed without merging**
