### PR TITLE
beaglebone/upnp-skeleton: add the missing MAC

### PR DESCRIPTION
**Pull request by mpvader**

### CODE REVIEW

**Comment by jhofstee** [comment]
and this, <modelName>CCGX</modelName>? Is that a feature or a copy/paste error?

**Comment by jhofstee** [comment]
likewise for the UDN, do we want to announce these devices as ccgx compatible?

**Comment by jhofstee** [comment]
apparently github eats <> tags, I meant the modelName tag

**Comment by mpvader** [comment]
See commit msg. My idea was to keep it simple, and same as Achilles

**Comment by mpvader** [comment]
I don't see an advantage in announcing as com.victronenergy.beaglebone.

Machine type is irrelevant for the other party that is searching.

**Comment by mpvader** [comment]
I see now that the commit msg got lost. It was something like:

Ccgx references (UDN, Modelname) are left as is on purpose. To keep this commit simple, and also same as Achilles.

**Pull request closed without merging**
