### PR TITLE
Update rpi-base.inc to include sc16is752-spi1.dtbo

### PR DESCRIPTION
**Pull request by herrfrei**
Overlay needed for RS485 on the Waveshare RS485 CAN HAT (B)

Link: https://www.waveshare.com/wiki/RS485_CAN_HAT_(B)

### CODE REVIEW

**Comment by mpvader** [comment]
Hi! Thank you for your interest and contribution!

I’ll get a colleague to check this out

@nmbath for you?

**Comment by jhofstee** [comment]
This is fine, you can simply include it.

**Comment by nmbath** [comment]
It can be included. There are probably a few other overlays that might make sense to include as well. I will get to them at some point ;)

**Comment by jhofstee** [comment]
included https://github.com/victronenergy/meta-victronenergy/commit/1ea66d16a4382dc2897f7483a9022b4ea653216d

**Pull request closed without merging**
